package org.example.idf_service.service;
import jakarta.persistence.EntityManager; import org.example.idf_service.config.RatesProperties; import org.example.idf_service.domain.*; import org.example.idf_service.dto.*; import org.example.idf_service.repository.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class TransactionService { private final TransactionRepository transactions; private final MonthLockRepository locks; private final LimitService limits; private final RateService rates; private final RatesProperties properties; private final EntityManager em;
 public TransactionService(TransactionRepository t,MonthLockRepository l,LimitService ls,RateService r,RatesProperties p,EntityManager em){transactions=t;locks=l;limits=ls;rates=r;properties=p;this.em=em;}
 @Transactional public void register(TransactionRequest request){ ZoneId zone=properties.monthZone(); LocalDate localDate=request.datetime().atZoneSameInstant(zone).toLocalDate(); LocalDate month=localDate.withDayOfMonth(1); acquireLock(request.account_from(),month,request.expense_category());
  BigDecimal usd=request.sum().multiply(rates.usdRate(request.currency_shortname(),localDate)).setScale(2,RoundingMode.HALF_UP); ExpenseLimit limit=limits.applicable(request.account_from(),request.expense_category(),request.datetime()); OffsetDateTime start=month.atStartOfDay(zone).toOffsetDateTime(); OffsetDateTime end=month.plusMonths(1).atStartOfDay(zone).toOffsetDateTime(); BigDecimal spent=transactions.sumForLimitMonth(request.account_from(),request.expense_category(),limit.getId(),start,end); boolean exceeded=spent.add(usd).compareTo(limit.getAmountUsd())>0; transactions.save(new ExpenseTransaction(request.account_from(),request.account_to(),request.currency_shortname(),request.sum().setScale(2,RoundingMode.HALF_UP),request.expense_category(),request.datetime(),usd,exceeded,limit)); }
 private void acquireLock(String account,LocalDate month,ExpenseCategory category){ if(locks.lock(account,month,category).isPresent())return; try { locks.saveAndFlush(new AccountMonthLock(account,month,category)); } catch(DataIntegrityViolationException ignored){ em.clear(); } locks.lock(account,month,category).orElseThrow(); }
 @Transactional(readOnly=true) public List<ExceededTransactionResponse> exceeded(String account){ return transactions.findExceededWithLimitAggregate(account).stream().map(t->new ExceededTransactionResponse(t.getAccountFrom(),t.getAccountTo(),t.getCurrency(),t.getAmount(),t.getCategory(),t.getOccurredAt(),t.getLimit().getAmountUsd(),t.getLimit().getEstablishedAt(),"USD")).toList(); }
}
